
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password:

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update
#      dialect: org.hibernate.dialect.MySQLInnoDBDialect


server:
  port: 8000
